lang1: en
lang2: de
sos_token: <sos>
eos_token: <eos>
max_length : 1_000
lower: True
batch_size: 128



encoder_embedding_dim: 256
decoder_embedding_dim: 256
hidden_dim: 512
n_layers: 2
encoder_dropout: 0.5
decoder_dropout: 0.5


n_epochs: 50
clip: 1.0
teacher_forcing_ratio:  0.5
