artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: "bentrevett/multi30k"
  raw_path: artifacts/data_ingestion/raw
  data_files:
    raw_data: artifacts/data_ingestion/raw/raw.json
    train: artifacts/data_ingestion/train.json
    validation: artifacts/data_ingestion/validation.json
    test: artifacts/data_ingestion/test.json
 

